# Generated by Django 5.1.1 on 2024-09-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program_heading", models.CharField(default="", max_length=100)),
                ("program_des", models.TextField()),
                (
                    "program_img",
                    models.FileField(
                        blank=True, default="", null=True, upload_to="gallery/"
                    ),
                ),
            ],
        ),
    ]
