# Generated by Django 5.1.1 on 2024-09-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_contact_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about_img",
                    models.FileField(
                        blank=True,
                        default="",
                        max_length=120,
                        null=True,
                        upload_to="faculty/",
                    ),
                ),
            ],
        ),
    ]
