# Generated by Django 5.1.1 on 2024-09-08 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_contacts"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contacts",
        ),
    ]
