# Generated by Django 5.0.6 on 2024-08-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_des',
            field=models.TextField(),
        ),
    ]
