# Generated by Django 5.0.6 on 2024-08-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_img', models.FileField(blank=True, default='', null=True, upload_to='\\media')),
            ],
        ),
    ]
