# Generated by Django 5.0.6 on 2024-08-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='about_img',
            field=models.FileField(blank=True, default=None, null=True, upload_to='about/'),
        ),
    ]
