# Generated by Django 5.0.6 on 2024-08-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_image_about_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
