# Generated by Django 5.0.6 on 2024-08-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_img',
            field=models.FileField(blank=True, default='', max_length=250, null=True, upload_to='about/'),
        ),
    ]
