# Generated by Django 5.1.1 on 2024-09-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0007_image_remove_about_about_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slogun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slogun_heading", models.CharField(default="", max_length=20)),
                ("slogun_des", models.TextField()),
            ],
        ),
    ]
