# Generated by Django 5.1.1 on 2024-09-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0008_slogun"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slogun",
            name="slogun_heading",
            field=models.CharField(default="", max_length=100),
        ),
    ]
